"""
Fine-Tuning Script for Kafe Nusantara AI Barista
Uses Unsloth + QLoRA for memory-efficient fine-tuning of Llama 3.2

Prerequisites:
  pip install unsloth transformers datasets peft trl

Usage:
  python scripts/fine-tune/train.py

Output:
  - LoRA adapter weights in ./kafi-lora/
  - Merged GGUF model for Ollama import
"""

import os
import json
import torch
from pathlib import Path

def check_dependencies():
    """Check if required packages are available."""
    missing = []
    for pkg in ["unsloth", "transformers", "datasets", "peft", "trl"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    
    if missing:
        print(f"❌ Missing packages: {', '.join(missing)}")
        print(f"   Install with: pip install {' '.join(missing)}")
        print(f"   For Unsloth: pip install 'unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git'")
        return False
    return True

def load_training_data(data_path: str):
    """Load JSONL training data generated by generate-training-data.ts"""
    from datasets import Dataset
    
    examples = []
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                examples.append(json.loads(line))
    
    print(f"📊 Loaded {len(examples)} training examples")
    return Dataset.from_list(examples)

def format_alpaca_prompt(example):
    """Format training example into Alpaca template."""
    return {
        "text": f"""### Instruction:
{example['instruction']}

### Input:
{example['input']}

### Response:
{example['output']}"""
    }

def train():
    """Main fine-tuning pipeline."""
    if not check_dependencies():
        return
    
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    
    # ─── Configuration ────────────────────────────────────────────────
    BASE_MODEL = "unsloth/Llama-3.2-1B-Instruct"   # Pre-quantized 4-bit
    MAX_SEQ_LENGTH = 2048
    LORA_RANK = 32          # LoRA rank (higher = more capacity to learn patterns)
    LORA_ALPHA = 32         # LoRA alpha (typically same as rank)
    EPOCHS = 5              # More epochs for small datasets to converge
    BATCH_SIZE = 4          # Per-device batch size
    GRADIENT_ACCUMULATION = 4  # Effective batch = 4 * 4 = 16
    LEARNING_RATE = 1e-4    # Slightly lower LR for more stable training
    OUTPUT_DIR = Path("./")
    DATA_DIR = Path("./")
    
    print("=" * 60)
    print("🧠 Kafi Fine-Tuning Pipeline")
    print("=" * 60)
    print(f"   Base Model:    {BASE_MODEL}")
    print(f"   LoRA Rank:     {LORA_RANK}")
    print(f"   Epochs:        {EPOCHS}")
    print(f"   Batch Size:    {BATCH_SIZE} x {GRADIENT_ACCUMULATION} = {BATCH_SIZE * GRADIENT_ACCUMULATION}")
    print(f"   Learning Rate: {LEARNING_RATE}")
    print(f"   GPU:           {'CUDA' if torch.cuda.is_available() else 'CPU (SLOW!)'}")
    if torch.cuda.is_available():
        print(f"   GPU Name:      {torch.cuda.get_device_name(0)}")
        print(f"   GPU Memory:    {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
    print("=" * 60)
    
    # ─── Step 1: Load Pre-Trained Model with QLoRA ────────────────────
    print("\n📥 Step 1: Loading pre-trained model with 4-bit quantization...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,             # Auto-detect (float16 for GPU, float32 for CPU)
        load_in_4bit=True,      # QLoRA: 4-bit quantization for memory efficiency
    )
    
    # ─── Step 2: Add LoRA Adapters ────────────────────────────────────
    print("🔧 Step 2: Adding LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",      # Attention
            "gate_proj", "up_proj", "down_proj",          # MLP
        ],
        lora_alpha=LORA_ALPHA,
        lora_dropout=0.0,       # No dropout for small datasets
        bias="none",
        use_gradient_checkpointing="unsloth",  # Memory optimization
    )
    
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"   Trainable params: {trainable:,} / {total:,} ({100*trainable/total:.2f}%)")
    
    # ─── Step 3: Load & Format Dataset ────────────────────────────────
    print("\n📊 Step 3: Loading training dataset...")
    data_path = DATA_DIR / "cafe-training-data.jsonl"
    
    if not data_path.exists():
        print(f"❌ Training data not found: {data_path}")
        print("   Run first: npx tsx scripts/generate-training-data.ts")
        return
    
    dataset = load_training_data(str(data_path))
    dataset = dataset.map(format_alpaca_prompt)
    
    # ─── Step 4: Configure Training ───────────────────────────────────
    print("\n🏋️ Step 4: Starting fine-tuning...")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        dataset_num_proc=2,
        packing=True,           # Pack short examples together for efficiency
        args=TrainingArguments(
            output_dir=str(OUTPUT_DIR),
            per_device_train_batch_size=BATCH_SIZE,
            gradient_accumulation_steps=GRADIENT_ACCUMULATION,
            warmup_steps=10,
            num_train_epochs=EPOCHS,
            learning_rate=LEARNING_RATE,
            fp16=not torch.cuda.is_bf16_supported() if torch.cuda.is_available() else False,
            bf16=torch.cuda.is_bf16_supported() if torch.cuda.is_available() else False,
            logging_steps=10,
            save_steps=50,
            save_total_limit=3,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            seed=42,
            report_to="none",
        ),
    )
    
    # ─── Step 5: Train! ───────────────────────────────────────────────
    stats = trainer.train()
    print(f"\n✅ Training complete!")
    print(f"   Training loss: {stats.training_loss:.4f}")
    print(f"   Total steps:   {stats.global_step}")
    
    # ─── Step 6: Save LoRA Adapter ────────────────────────────────────
    lora_path = OUTPUT_DIR / "kafi-lora"
    model.save_pretrained(str(lora_path))
    tokenizer.save_pretrained(str(lora_path))
    print(f"\n💾 LoRA adapter saved to: {lora_path}")
    
    # ─── Step 7: Export to GGUF (for Ollama) ──────────────────────────
    print("\n📦 Step 7: Exporting to GGUF format...")
    gguf_path = OUTPUT_DIR / "kafi-finetuned"
    
    # Merge LoRA into base model and quantize
    model.save_pretrained_gguf(
        str(gguf_path),
        tokenizer,
        quantization_method="q4_k_m",  # Good balance of size/quality
    )
    print(f"💾 GGUF model saved to: {gguf_path}")
    
    # ─── Step 8: Generate Ollama Modelfile ────────────────────────────
    modelfile_content = f"""# Fine-tuned Kafi model for Kafe Nusantara
FROM {gguf_path}/unsloth.Q4_K_M.gguf

PARAMETER temperature 0.1
PARAMETER top_p 0.85
PARAMETER top_k 30
PARAMETER num_ctx 3072
PARAMETER stop "<|eot_id|>"

SYSTEM \"\"\"
Anda adalah Kafi, barista virtual di Kafe Nusantara.
Jawab HANYA berdasarkan DAFTAR MENU yang diberikan.
DILARANG mengarang menu yang tidak ada di daftar.
Gunakan Bahasa Indonesia santai dan ramah.
Sertakan [ORDER:Nama Menu] jika pelanggan memesan.
\"\"\"
"""
    modelfile_path = OUTPUT_DIR / "Modelfile.finetuned"
    modelfile_path.write_text(modelfile_content)
    
    print(f"\n{'=' * 60}")
    print("🎉 Fine-tuning pipeline complete!")
    print(f"{'=' * 60}")
    print(f"\nTo use the fine-tuned model in Ollama:")
    print(f"  1. ollama create kafi-ft -f {modelfile_path}")
    print(f"  2. Set LLM_TYPE=kafi-ft in .env")
    print(f"  3. Update src/lib/ai.ts to add 'kafi-ft' case")

if __name__ == "__main__":
    train()
